### PR TITLE
feat(*) Reduce extra code used by imports

### PR DESCRIPTION
**Pull request by kakarot-dev**
Idk if ive missed something, pls do check thoroughly

### CODE REVIEW

**Review by Mirdukkk — CHANGES_REQUESTED** [review]
you missed src/entities/index.ts, please change it too

**Review by Mirdukkk — APPROVED** [review]

**Comment by kakarot-dev** [comment]
Done

**Comment by Mirdukkk** [comment]
thanks for contributing!

**Comment by kakarot-dev** [comment]
np

**Pull request merged**
