### PR TITLE
fix(contributing): typo & grammatical errors

### PR DESCRIPTION
**Pull request by TheLionCub**

### CODE REVIEW

**Review by TheLionCub — COMMENTED** [review]
One more fix

**Comment by Mirdukkk** [comment]
if there are more fixes, add them to this PR, do not create new ones. if not, please let us know and PR will be merged.

**Comment by TheLionCub** [comment]
Haven't found anything serious in .md files requiring correction (but at least for now).

**Comment by Mirdukkk** [comment]
as I understand it this is ready for merge.

**Pull request merged**
